id: IB7E28A0B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:57:33+00:00'
last_modified: '2022-06-08T11:30:32.984717+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4257
  title: བཀའ་གདམས་གསར་རྙིང་གི་ཆོས་འབྱུང་ཡིད་ཀྱི་མཛེས་རྒྱན།（རྔ་ཡུལ་ཀིརྟི་དགོན་གྱི་གློག་ཀླད་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ADB5:
      image_group_id: I1KG4983
      title: ''
      total_pages: 296
      order: 1
      base_file: ADB5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
