id: opecha:P009505
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4257
  title: བཀའ་གདམས་གསར་རྙིང་གི་ཆོས་འབྱུང་ཡིད་ཀྱི་མཛེས་རྒྱན།（རྔ་ཡུལ་ཀིརྟི་དགོན་གྱི་གློག་ཀླད་པར་མ།）
  volume: ''
  author: ''
