id: P009505
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:33:34.393143
source_metadata:
  id: bdr:W1KG4257
  title: བཀའ་གདམས་གསར་རྙིང་གི་ཆོས་འབྱུང་ཡིད་ཀྱི་མཛེས་རྒྱན།（རྔ་ཡུལ་ཀིརྟི་དགོན་གྱི་གློག་ཀླད་པར་མ།）
  author: ''
  volumes:
    899f23f8845b4e52b459d0112f39deda:
      image_group_id: I1KG4983
      title: ''
      volume_number: 1
      total_pages: 296
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
